### ISSUE TITLE
Not able to use middlewares outside the App constructor.

### ISSUE THREAD

**Issue by mustafashaikh4714** [CallbacKiran/tsxp#1]
I am trying to apply a conditional-based middleware besides the App constructor in App.ts.

```
export const { app, listen } = new App(options)

// a normal conditional middleware
app.use(customMiddleware)         // Not applying globally.
```

On the other side if I am passing the same middleware in the App constructor it is applying.
`export const { app, listen } = new App({ middlewares: [customMiddleware] })   // works.
`

@kiran-bhalerao Please address the issue

**Comment by kiran-bhalerao** [comment]
Updated typescript type of **app** instance, please update @tsxp/core to the latest version.

I don't know your case here, but I think there is no need to do `app.use(customMiddleware) `.
You can pass your middleware directly to the middlewares option of App constructor like, `middlewares: [customMiddleware]`.

In express.js, we need to attach our middlewares before attaching the routes. The @tsxp/core's internal code attaches the routes before your `app.use()` and that's the reason your middleware was not attached to **app**.

**Comment by mustafashaikh4714** [comment]
@kiran-bhalerao thanks for the update!
